language: haskell
before_install:
  - cabal install --only-dependencies $mode
  - cabal install hlint

install:
  - cabal configure $mode
  - cabal build

script:
  - hlint -c . --ignore="Parse error"
  - cabal test --show-details=always

env:
  - mode="--enable-tests"
