name: th-printf
version: 0.6.1
synopsis: Quasiquoters for printf
description: |
  Quasiquoters for printf: string, bytestring, text.
author: Jude Taylor
maintainer: me@jude.xyz
tested-with: GHC == 7.8.4, GHC == 7.10.3, GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.3
extra-source-files: CHANGELOG.md
category: Text
github: pikajude/th-printf

ghc-options: -Wall

flags:
  werror:
    description: Build with -Werror
    default:     False
    manual:      True

when:
  - condition: impl(ghcjs)
    dependencies: [primitive == 0.6.3.0]
  - condition: flag(werror)
    ghc-options: -Werror

dependencies:
  - base == 4.*

custom-setup:
  dependencies:
    - Cabal == 2.4.*
    - base

library:
  source-dirs: [src, parser]
  exposed-modules:
    - Language.Haskell.Printf
    - Language.Haskell.Printf.Lib
  dependencies:
    - charset
    - containers
    - microlens-platform
    - mtl
    - parsec
    - semigroups
    - template-haskell
    - th-lift
    - transformers

tests:
  format:
    source-dirs: tests
    main: format.hs
    dependencies:
      - HUnit
      - QuickCheck
      - hspec
      - template-haskell
      - th-printf
    when:
      - condition: impl(ghcjs)
        dependencies: [hspec-core == 2.4.8]
